#!/bin/sh

# TODO: Make everything module
# Ensure that we are in root
cd "$HOME"

sudo -v 

# TODO: do something for macos (brain needs to think)
# system_type=$(uname -s)

# if [ "$system_type" = "Darwin" ]; then
#     echo "pinentry-program /usr/local/bin/pinentry-mac" > ~/.gnupg/gpg-agent.conf
#   # install homebrew if it's missing
#     if ! command -v brew >/dev/null 2>&1; then
#         echo "Installing homebrew"
#         /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#     fi


#     if [ "`echo -n`" = "-n" ]; then
#         n=""
#         c="\c"
#     else
#         n="-n"
#         c=""
#     fi

#     # note to future overclockedllama
#     # brew bundle dump && mv Brewfile ~/.config/brewfile
#     echo $n "Please enter if you would like to install ALL of overclockedllama's programs (y/n)? "
#     read answer
#     if [ "$answer" != "${answer#[Yy]}" ] ;then
#         if [ -f "$HOME/.config/brewfile" ]; then
#             echo "Updating homebrew bundle"
#             brew bundle --file=~/.config/brewfile
#         fi
#     else
#         brew install vim zsh-autosuggestions zsh-syntax-highlighting coreutils pinentry-mac 2>/dev/null
#         brew cask install visual-studio-code 2>/dev/null
#     fi


#     if [ -d "$HOME/.config/iterm2" ]; then
#         echo "Setting iTerm preference folder"
#         defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
#     fi
#     osascript -e "on run(argv)" -e 'tell application "System Events" to tell every desktop to set picture to argv' -e 'end' $HOME/.config/wallpaper.png
# fi

if command -v apt-get >/dev/null 2>&1; then
    echo -e "[1/7] 🔄\tUpdate System..."
    sudo apt-get update
    echo -e "[2/7] 🔗\tInstall dependencies..."
    sudo apt-get install vim zsh zsh-autosuggestions zsh-syntax-highlighting -y
fi

if command -v zsh >/dev/null 2>&1; then
    if [ -d "$Home/.oh-my-zsh" ]; then
        rm -r -f $Home/.oh-my-zsh

    fi
    echo -e "[3/7] 📥\tInstall oh-my-zsh..."
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    echo -e "[4/7] 📥\tInstall Spaceship-Prompt..."
    git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1

    echo -e "[4/7] 🔗\tCreate Symlink for spaceship.zsh-theme to "$ZSH_CUSTOM"..."
    ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme" 
fi

if command -v nvm >/dev/null 2>&1; then
    echo -e "[5/7] 📥\tInstalling nvm..."
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
fi

if command -v node >/dev/null 2>&1; then
    echo -e "[6/7] 📥\tInstalling node..."
    nvm install stable
fi

if command -v yarn >/dev/null 2>&1; then
    echo -e "[7/7] 📥\tInstalling yarn..."
    npm install --global yarn
    echo -e "[7/7] 🔧\tCustom Settings..."
    echo -e "[7/7] 😃\tDo you want to enable Emojis for yarn? (y/n)"
    read answer
    if [ "$answer" != "${answer#[Yy]}" ] ;then
        yarn config set -- --emoji true
    fi
fi

# TODO: get latest release from github for balena cli  
# curl --silent "https://api.github.com/repos/USER/REPO/releases/latest" | # Get latest release from GitHub api
#     grep '"tag_name":' |                                                 # Get tag line
#     sed -E 's/.*"([^"]+)".*/\1/' |
#     xargs -I {} curl -sOL "https://github.com/USER/REPO/archive/"{}'.tar.gz'


echo "Changing shell to zsh boi"
chsh -s `which zsh`
echo "You might need to log out and back in for changes to take effect"

#TODO: yadm encrypt https://yadm.io/docs/encryption
#echo "Are you overclockedllama?"
#read ans

#if [ "$ans" != "${ans#[Yy]}" ] ;then
    # user said yes

#    yadm decrypt ||
#    (
#        export GPG_TTY=$(tty) &&
#        yadm decrypt ||
#        echo unable to decrypt
#    )
#fi
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "https://github.com/daribock/dotfiles.git"

zsh