#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

TextColorBlue='\033[1;34m'
TextColorRed='\033[0;31m'
TextColorOrange='\033[1;31m'
TextColorYellow='\033[1;33m'
TextColorGreen='\033[0;32m'
TextColorNone='\033[0m'

sudo -v 

# echo -e "${TextColorBlue}[ Info ]${TextColorNone}\tInit submodules"
# yadm submodule update --recursive --init

# TODO: do something for macos (brain needs to think)
# system_type=$(uname -s)

# if [ "$system_type" = "Darwin" ]; then
#     echo "pinentry-program /usr/local/bin/pinentry-mac" > ~/.gnupg/gpg-agent.conf
#   # install homebrew if it's missing
#     if ! command -v brew >/dev/null 2>&1; then
#         echo "Installing homebrew"
#         /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#     fi


#     if [ "`echo -n`" = "-n" ]; then
#         n=""
#         c="\c"
#     else
#         n="-n"
#         c=""
#     fi

#     # note to future overclockedllama
#     # brew bundle dump && mv Brewfile ~/.config/brewfile
#     echo $n "Please enter if you would like to install ALL of overclockedllama's programs (y/n)? "
#     read answer
#     if [ "$answer" != "${answer#[Yy]}" ] ;then
#         if [ -f "$HOME/.config/brewfile" ]; then
#             echo "Updating homebrew bundle"
#             brew bundle --file=~/.config/brewfile
#         fi
#     else
#         brew install vim zsh-autosuggestions zsh-syntax-highlighting coreutils pinentry-mac 2>/dev/null
#         brew cask install visual-studio-code 2>/dev/null
#     fi


#     if [ -d "$HOME/.config/iterm2" ]; then
#         echo "Setting iTerm preference folder"
#         defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
#     fi
#     osascript -e "on run(argv)" -e 'tell application "System Events" to tell every desktop to set picture to argv' -e 'end' $HOME/.config/wallpaper.png
# fi

if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get install vim zsh-autosuggestions zsh-syntax-highlighting zsh -y
fi

if command -v zsh >/dev/null 2>&1; then
    if [ -d "$Home/.oh-my-zsh" ]; then
        rm -r -f $Home/.oh-my-zsh
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

        git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1

        ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme" 
    fi
fi

if command -v pacman >/dev/null 2>&1; then
    sudo pacman -Syu gvim zsh-autosuggestions zsh-syntax-highlighting zsh --noconfirm
fi

echo "Changing shell to zsh boi"
chsh -s `which zsh`
echo "You might need to log out and back in for changes to take effect"

#TODO: yadm encrypt https://yadm.io/docs/encryption
#echo "Are you overclockedllama?"
#read ans

#if [ "$ans" != "${ans#[Yy]}" ] ;then
    # user said yes

#    yadm decrypt ||
#    (
#        export GPG_TTY=$(tty) &&
#        yadm decrypt ||
#        echo unable to decrypt
#    )
#fi
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "https://github.com/daribock/dotfiles.git"

zsh