name: linter
on: push

jobs:
  lint:
    name: Lint all the stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # https://github.com/github/super-linter/blob/master/docs/disabling-linters.md
      - name: Linter
        uses: docker://github/super-linter:v3
        env: 
          FILTER_REGEX_EXCLUDE: .*.config/yadm/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
